### ISSUE TITLE
Txt in Chat Room not Appearing.

### ISSUE THREAD

**Issue by kevinmurphy77** [Team357/cityonchain#2]
https://whatsonchain.com/tx/0103f2a299b0ef00298082b5b1dc2ee06460ca1404ac757bd86fc2260b7e02c7

https://whatsonchain.com/tx/ea7924253301fa3d58215f5a11c90b52a7a57edd94acb1a7290be2a2efe6cc58

===========
Those are 2 , of  4 action that failed to happen.

we can see the TX , we paid for the Text but it never showed up in the chat room.
( Twice in  -city/Montreal , Once in -city/Papeete, and i think it happen somewhere else sometime ago )

Please Fix !
People will be scare to post in chat !

**Comment by asinen** [comment]
Hi kevin, it's a bug from money button. We are trying to solve it together with MB. And we are also trying to read the transaction data from the chain to avoid this problem. Needs some time. We will fix it ASAP.
BTW, could you give us your MB account? We will return you the BSV that you paid but message failed

**Comment by kevinmurphy77** [comment]
hi Asine , thanks for the quick reply.
my moneybutton is ;
2733@moneybutton.com

i did notice something in the Bug Pattern.

The Failed Action happen when i can't see my +0.01 nor my minus -0.01 in my  Social Balance or City Balance.
BUT, it Do appear, in the MoneyButton as a successful transaction.
But, not in the CoC Account Info.

If i can see the +0.01 / -0.01 , the Text in the Chat room , will be , successful.

That is the pattern i notice for a super-quick.
 ( i do troubelshoot/fix high rise Elevator as my dayjob since 15years.   pattern are powerful )

Failed transaction happen Twice in Montreal , once in Papeete , and somewhere else that i lost track but it's ok.


GREAT WORK
WE LOVE THIS POWERFUL CoC !

[http://graphics.hotmail.com/emwink.gif]-Bye-Bye-[http://graphics.hotmail.com/emwink.gif]
[http://graphics.hotmail.com/ememail.gif]Couriel[http://graphics.hotmail.com/ememail.gif]:Kevin_Murphy77@hotmail.com

________________________________
De : Asine <notifications@github.com>
Envoyé : 17 août 2019 03:02
À : Team357/cityonchain <cityonchain@noreply.github.com>
Cc : kevinmurphy77 <kevin_murphy77@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Team357/cityonchain] Txt in Chat Room not Appearing. (#2)


Hi kevin, it's a bug from money button. We are trying to solve it together with MB. And we are also trying to read the transaction data from the chain to avoid this problem. Needs some time. We will fix it ASAP.
BTW, could you give us your MB account? We will return you the BSV that you paid but message failed

**Comment by asinen** [comment]
Thanks for the bug pattern  Kevin. We found most times for the bug, MB didn't return the success message of the payment to us, so we took it as a failure and no transaction records show in CoC balance. We have to fix the problem with MB. Thank you very much for supporting us.
BTW, we sent $0.05 to your account, please check.

**Comment by kevinmurphy77** [comment]
received 0.05$, thanks you verymuch.

i can see the unlimited potential of CoC ,
and i took myself 303 cities and i sold some.   but mainly for my incoming 30th birthday , i successfully grab MONTREAL for 499$.
i'm also on a intencive GEOGRAPHY CLASS with my 4years old daughter so she can rock the boat on CoC in a very near future.

See you soon in a city somewhere !!


[http://graphics.hotmail.com/emwink.gif]-Bye-Bye-[http://graphics.hotmail.com/emwink.gif]
[http://graphics.hotmail.com/ememail.gif]Couriel[http://graphics.hotmail.com/ememail.gif]:Kevin_Murphy77@hotmail.com

________________________________
De : Asine <notifications@github.com>
Envoyé : 17 août 2019 13:12
À : Team357/cityonchain <cityonchain@noreply.github.com>
Cc : kevinmurphy77 <kevin_murphy77@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Team357/cityonchain] Txt in Chat Room not Appearing. (#2)


Thanks for the bug pattern Kevin. We found most times for the bug, MB didn't return the success message of the payment to us, so we took it as a failure and no transaction records show in CoC balance. We have to fix the problem with MB. Thank you very much for supporting us.
BTW, we sent $0.05 to your account, please check.

**Comment by asinen** [comment]
Very glad that you enjoy on CoC : )  Happy Birthday！ See you
